apiVersion: apps/v1
kind: Deployment
metadata:
  name: "maa-nginx"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "maa-nginx"
      argo: "true"
  template:
    metadata:
      labels:
        app: "maa-nginx"
        argo: "true"
    spec:
      containers:
        - name: maa
          image: nginx:latest
